name = "ii-agent-frontend"
compatibility_date = "2024-09-01"

[env.production]
name = "ii-agent-frontend"

[env.preview]  
name = "ii-agent-frontend-preview"

# Pages configuration
pages_build_output_dir = ".next"

# Environment variables that will be available during build
# You can set these in the Cloudflare dashboard or via wrangler secrets
[env.production.vars]
NEXT_PUBLIC_API_URL = ""
NEXT_PUBLIC_WS_URL = ""

[env.preview.vars]
NEXT_PUBLIC_API_URL = ""  
NEXT_PUBLIC_WS_URL = ""

# Build configuration
[build]
command = "npm run build"

# Node.js compatibility
compatibility_flags = ["nodejs_compat"]