name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'frontend/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Frontend to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Build Next.js application
        working-directory: ./frontend
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_WS_URL: ${{ secrets.NEXT_PUBLIC_WS_URL }}
          
      - name: Deploy to Cloudflare Pages (Preview)
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'preview')
        working-directory: ./frontend
        run: npx wrangler pages deploy .next --project-name ii-agent-frontend --env preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Deploy to Cloudflare Pages (Production)
        if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
        working-directory: ./frontend
        run: npx wrangler pages deploy .next --project-name ii-agent-frontend --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Add deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Frontend successfully deployed to Cloudflare Pages" >> $GITHUB_STEP_SUMMARY
          echo "🌐 **Project**: ii-agent-frontend" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ github.event_name }}" == "pull_request" || ("${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.environment }}" == "preview") ]]; then
            echo "📦 **Environment**: Preview" >> $GITHUB_STEP_SUMMARY
            echo "🔗 **URL**: https://$(git rev-parse --short HEAD).ii-agent-frontend.pages.dev" >> $GITHUB_STEP_SUMMARY
          else
            echo "📦 **Environment**: Production" >> $GITHUB_STEP_SUMMARY  
            echo "🔗 **URL**: https://ii-agent-frontend.pages.dev" >> $GITHUB_STEP_SUMMARY
          fi